Name:           perl-Image-ExifTool-Location
Version:        0.0.4
Release:        1%{?dist}
Summary:        Easy setting, getting of an image's location information
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Image-ExifTool-Location/
Source0:        http://www.cpan.org/authors/id/A/AN/ANDYA/Image-ExifTool-Location-v%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Image::ExifTool) >= 6.76
BuildRequires:  perl(Test::More)
BuildRequires:  perl(version)
Requires:       perl(Image::ExifTool) >= 6.76
Requires:       perl(Test::More)
Requires:       perl(version)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Image::ExifTool is a versatile module for reading and writing EXIF data in
a number of image formats. This module extends its interface adding methods
that simplify the reading and writing of GPS location information.

%prep
%setup -q -n Image-ExifTool-Location-v%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
#make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Mon Jul 02 2018 Jonathan Gazeley <me@jonathangazeley.com> 0.0.4-1
- Specfile autogenerated by cpanspec 1.78.
